title: Biomechanical RL at S<sup>3</sup>CIX
description: Biomechanical RL as a Methodological Direction for Computational Interaction?
show_downloads: true
google_analytics: G-8BL0XYF2HZ
theme: jekyll-theme-cayman