title: Workshop on Computational User Models for Work
description: User Models as Methodological Direction for Computational Interaction?
show_downloads: true
google_analytics: G-8BL0XYF2HZ
theme: jekyll-theme-cayman